### ISSUE TITLE
Please bump dependencies

### ISSUE THREAD

**Issue by 0323pin** [Byron/crates-io-cli-rs#11]
Hi, me again ...

Would it be possible to bump the crate dependencies here?
There is an issue building `libgit2-sys`-0.14.2+1.5.1 that has been fixed on the 1.6.x series.
Currently our package is broken :(

Regards

**Comment by Byron** [comment]
Hello there!

I wasn't aware somebody is using this, or some package depends on it.
Oh well, [here is the update](https://github.com/Byron/crates-io-cli/releases/tag/v4.0.2).

Cheers

**Comment by 0323pin** [comment]
Thanks!

We actually provide a pre-compiled binary for it.
Available from our repositories, https://pkgsrc.se/www/crates-io-cli 😄
