### ISSUE TITLE
Allow copying versions from cli

### ISSUE THREAD

**Issue by mainrs** [Byron/crates-io-cli-rs#5]
Maybe some shortcut for copying 0-9 would be nice, like Ctrl+(0-9) or maybe another subcommand of search. This would make the web interface absolete as you could easily look for versions from the terminal.

**Comment by ghost** [comment]
Could you explain how you would use it? Do you mean the crate version that should be copied? Right now it only shows the most recent available version, which doesn't map to 'versions' as used in the subject.

The idea right now is to press `Ctrl+o` then `<number>` and copy the desired value from the browser. For me it was just meant to be a search interface, then one can jump right to the interesting crate in the browser, and take it from there.

If you can map the user journey you think of here, something interacting with the clipboard can be implemented.

**Comment by mainrs** [comment]
Ah ok. My idea was to kind of act as a second frontend where you could simply type `crates search diesel`, select `diesel` and it copies the version value right into the clipboard without the need to actually open up a browser tab. Kind of a faster version of `Ctrl+o`. Maybe something like `Ctrl-v` and basically having the same menu "pop up" where you select an entry.

**Comment by ghost** [comment]
Thanks! What I don't understand is what the value is in having the version number in the clipboard. For example, I use `cargo add` to add any crate by name, with the version set to the latest available. Thus from my point of view the name would be more useful. However, there is obviously something I don't see.

**Comment by mainrs** [comment]
Wait I didn't know the command existed. Wow nice! It would basically be the same as cargo add :smile:
