### ISSUE TITLE
packaged for NetBSD

### ISSUE THREAD

**Issue by 0323pin** [Byron/crates-io-cli-rs#9]
FYI, it's now available on NetBSD, https://mail-index.netbsd.org/pkgsrc-changes/2023/03/17/msg271117.html

To install it simply run `pkgin install crates-io-cli`.

Regards

**Comment by Byron** [comment]
Thank you very much! 

Please feel free to send a PR to add this installation option to the README.

**Comment by 0323pin** [comment]
Thanks, https://github.com/Byron/crates-io-cli/pull/10
